# Generated by Django 3.1.6 on 2021-03-20 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('follower_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='default.jpg', upload_to='follower')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('season', models.CharField(choices=[('Summer', 'Summer'), ('Spring', 'Spring'), ('Fall', 'Fall'), ('Winter', 'Winter')], default='Summer', max_length=250)),
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(default='default.jpg', upload_to='trip')),
                ('location', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TripFollower',
            fields=[
                ('trip_follower_id', models.AutoField(primary_key=True, serialize=False)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.follower')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.trip')),
            ],
        ),
    ]
