# Generated by Django 3.1.6 on 2021-03-20 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripfollower',
            name='follower',
            field=models.ForeignKey(db_column='follower_id', on_delete=django.db.models.deletion.DO_NOTHING, to='main.follower'),
        ),
    ]
