# Generated by Django 3.1.6 on 2021-03-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210320_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='follower_id',
            field=models.AutoField(db_column='follower_id', primary_key=True, serialize=False),
        ),
    ]
